module.exports = {
    baseURL: 'http://localhost:3001/api/v1',
    customer: '/customer',
    customer1: 'customer',
    feedback: '/feedback',
    feedback1: 'feedback',
    guest: '/guest',
    login: '/login',
    new:'/new',
    reception: '/reception',
    restaurant: '/restaurant',
    restaurant1: 'restaurant',
    room: '/room',
    slash: '/',
}